lane :bundletool_test do
  bundletool(
    verbose: true,
    bundletool_version: '1.10.0',
    aab_path: 'resources/example.aab',
    apk_output_path: "resources/bundletool_temp/universal_apk/myapk.apk"
  )
end
